### ISSUE TITLE
check_bird_bgp: Render performance data

### ISSUE THREAD

**Issue by mrimann** [BarbarossaTM/icinga2-plugins#5]
Hi

I'm playing with the `check_bird_bgp` check and I'm missing the output of performance data. I'd like to collect these over time, e.g. the number of accepted/exported, rejected and filtered routes per BGP session.

I see theses are already "read" in the code and used. But shown in the output only in case of WARNING or CRITICAL state (and not as machine readable data but before the status line). So the data is here - it would just be added to the output.

Any chance to get this added to the check script?

Cheers,
Mario

**Comment by mrimann** [comment]
@BarbarossaTM FYI: It's not yet ready, for now it just works when checking single sessions with `--session`. For "check all sessions" scenario, this needs some more changes I guess.

**Comment by BarbarossaTM** [comment]
Looks like you're looking into this :-) I'm happy to add this and saw you've already opened a PR, thanks for that :-)

**Comment by mrimann** [comment]
Ah, I missed to mention that after my "it's not ready" comment, I finalized the feature + the merge request https://github.com/BarbarossaTM/icinga2-plugins/pull/7 is now basically ready for a test from your side. Sorry :-/
