### ISSUE TITLE
check_bird_bgp: There's no birdc6 anymore

### ISSUE THREAD

**Issue by mrimann** [BarbarossaTM/icinga2-plugins#6]
Running the check on Ubuntu 22.04 and Bird 2.x - adding the `--proto 6` flag when invoking the check script, it' errors out because there's no `birdc6` binary anymore.

**Comment by BarbarossaTM** [comment]
Right now I don't have a use case for bird 2 (yet) and currently don't have the time to look into this. That said, I'm happy to merge a PR which adds support for `bird2` :-)

Depending on how involved the changes required for also supporting `bird2` are (which I can't predict right now), it might be worth making a copy of the script and have one for `bird1` and one for `bird2`. If it's straight forward to support both bird versions and handle the differences internally a `-2` command line option might be a nicer way :-)

On 2nd thought: It's likely better to make a copy and update that to "just" think in sessions and report the AFIs transported over that session, as bird2 allows having exchanging routing information for multiple or a different AFI compared to the one the BGP session is established on. So I believe the concept of IPv4 vs. IPv6 does not apply anymore.

I think it's even worth creating a new directory `check_bird2_bgp` to clearly separate the two checks and approaches.

**Comment by mrimann** [comment]
Since https://github.com/BarbarossaTM/icinga2-plugins/pull/8 was merged, I think this ist resolved and will thus close the issue.
