### ISSUE TITLE
check_bird2_bgp: Output of performance data "wrong"

### ISSUE THREAD

**Issue by mrimann** [BarbarossaTM/icinga2-plugins#9]
Output is not interpreted properly by Icinga2 / Nagios:

![image](https://user-images.githubusercontent.com/1093784/235182516-7552bd4c-e7b5-4ad5-9a4e-731cd84b3849.png)

**Comment by mrimann** [comment]
As far as I get it, there must not be spaces - otherwise Icinga2 (and Nagios) treat that output as additional human-readable output, but not as machine interpretable numerical values.

**Comment by mrimann** [comment]
OK, it was not the whitespace issue intially thought... It's ":" vs. "=" between variable name + value.

With this change, the output looks like this in Icinga2 and is what we initially wanted to achieve:

![image](https://user-images.githubusercontent.com/1093784/235184688-0bbad42d-96a2-482b-a05f-d5eb619fe173.png)

**Comment by BarbarossaTM** [comment]
Great find, thanks for fixing this!
